export const objectives = [{
  title :"2022, nos engagements",
  subtitle:"",
  link: "/",
  color: "#15514f",
  ico: "/favicon.png",
}, 
{
  title :"Certificat écocert",
  subtitle:"De nos produits pour l'agriculture biologique",
  link: "/",
  color: "#e38a70",
  ico: "/favicon.png",
}, 
{
  title :"22 200 tonnes de pesticides évités",
  subtitle:"",
  link: "/",
  color: "#cfcdce",
  ico: "/favicon.png",
}, 
{
  title :"95% de nos composants d'origine naturelle",
  subtitle:"Formulation de nos solutions phéromonales biologiques",
  link: "/",
  color: "#e38a70",
  ico: "/favicon.png",
}, 
{
  title :"100% de nos emballages en cartons recyclés",
  subtitle:"",
  link: "/",
  color: "#cfcdce",
  ico: "/favicon.png",
}, 
{
  title :"5% de baisse de notre consommation énergétique",
  subtitle:"",
  link: "/",
  color: "#15514f",
  ico: "/favicon.png",
}]