query GetPinnedProducts {
	options {
		optionsPage {
			products {
				pinned {
					... on Product {
						databaseId
						title
						uri
						slug
						data_product {
							featured {
								sourceUrl
								sizes
								srcSet
							}
							type {
								name
							}
						}
					}
				}
			}
		}
	}
}
