query GetPinnedProducts {
	options {
		optionsPage {
			pinnedproducts {
				... on Product {
					databaseId
					title
					uri
					slug
					data_product {
						featured {
							sourceUrl
							sizes
							srcSet
						}
					}
				}
			}
		}
	}
}
