query GetAllProducts {
	types {
		nodes {
			name
			slug
			count
		}
	}
	products {
		edges {
			node {
				title
				uri
				slug
				data_product {
					description
					type {
						name
						slug
						uri
					}
					featured {
						sourceUrl
						sizes
						srcSet
					}

					gallery {
						sourceUrl
						sizes
						srcSet
					}
				}
			}
		}
	}
}
